# Generated by Django 2.0.1 on 2018-01-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180128_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='death_of_birth',
            new_name='date_of_death',
        ),
    ]
