# Generated by Django 2.0.1 on 2018-02-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180203_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_edit', 'Make some changes...'), ('see_all_borrowed', 'See all borrowed'))},
        ),
    ]
